### ISSUE TITLE
Failed to load config screen

### ISSUE THREAD

**Issue by MinecraftMoments** [The-Fireplace-Minecraft-Mods/Textbook#19]
### Mod Version

2.2.2 for 1.20.1

### What mod loader(s) are you seeing the problem on?

Fabric

### Problem Description

![image](https://github.com/The-Fireplace-Minecraft-Mods/Textbook/assets/84159674/bcf11ea0-88cf-4b5a-bf08-aaa0c515ee78)
Went to check for if the mod was there, saw it was, and then noticed it couldnt load the editor settings.

**Comment by KeFiKkK** [comment]
### Install the Mod Menu plugin

**Comment by Fireflasher21** [comment]
> ### Install the Mod Menu plugin

not really helpful advice to install a plugin on client side

> ### Mod Version
> 
> 2.2.2 for 1.20.1
> ### What mod loader(s) are you seeing the problem on?
> 
> Fabric
> ### Mod Loader Version
> 
> _No response_
> ### Problem Description
> 
> ![image](https://private-user-images.githubusercontent.com/84159674/289282429-bcf11ea0-88cf-4b5a-bf08-aaa0c515ee78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTE4NjAsIm5iZiI6MTcyMjM1MTU2MCwicGF0aCI6Ii84NDE1OTY3NC8yODkyODI0MjktYmNmMTFlYTAtODhjZi00YjVhLWJmMDgtYWFhMGM1MTVlZTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE0NTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMTM4ZTE5NDUxMzEzZWZkZWVlMjhjNzdjODEzYjdiMjYzNWFiMmRiN2MxMDFjYjY2ZWZjNzk5MWM4NmEwMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EveGg5LMJmuFYkohWeVF2HuUsLifpXUQM6MsdHj2-_I) Went to check for if the mod was there, saw it was, and then noticed it couldnt load the editor settings.
> ### Steps To Reproduce
> 
> _No response_
> ### Crash Report or Error Logs
> 
> _No response_
> ### Additional Information
> 
> _No response_

There was an issue with the library which we used to create the config screen. There is now a new [Version](https://modrinth.com/mod/fireplace-lib/version/7.1.2+1.20.1+fabric)
